### ISSUE TITLE
Manage subdependencies that do not have a dependencmake file

### ISSUE THREAD

**Issue by pzehner** [pzehner/dependencmake#1]
Eventually, we could have something like this:

```yaml
dependencies:
  - name: My dependency
    url: file://my_server/my_dep.zip
    cmake_args: -DUSE_MPI=ON
    dependencies:
      - name: My subdependency
        url: http://my_repo/my_other_dep.git
        git_hash: 25481515
```
